name: LeetCode Sync
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # Runs daily at 8:00 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: solutions # Optional: Saves files to a specific folder
          verbose: true
